[project]
name = "isd-cp-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "rich[jupyter]>=14.2.0",
    "scipy>=1.16.3",
    "torch>=2.9.1",
]
